name: Build and Test contracts

on:
  - push
  - pull_request

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn

    - name: Install node dependencies
      run: yarn install
    - name: Build and test contracts
      env:
        ETH_INFURA_RPC_URL: ${{ secrets.ETH_INFURA_RPC_URL }}
      run: |
        yarn hardhat compile
        yarn hardhat test
