name: Build and Test contracts

on:
  - push
  - pull_request

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          ~/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn

    - name: Install node dependencies
      run: yarn install
    - name: Build and test contracts
      run: |
        yarn build
        yarn test
